name = "SimpleLattices"
uuid = "ce2437d6-9709-47f6-b5a7-5bf524fd8b96"
authors = ["Nicolas Loizeau"]
version = "1.0.0-DEV"


[extensions]
GLMakieSimpleLatticesExt = "GLMakie"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
GLMakie = "0.13.8"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[targets]
test = ["Test"]
